FROM ubuntu:20.04

SHELL [ "/bin/bash" , "-c" ]

RUN apt update && \
    apt upgrade -y 

RUN apt install vim -y
RUN apt install build-essential -y
RUN apt install -y python3
RUN apt install python3-pip -y